// <auto-generated />
namespace BEFLSPR.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ShowForAll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShowForAll));
        
        string IMigrationMetadata.Id
        {
            get { return "201609150902588_ShowForAll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
