// <auto-generated />
namespace BEFLSPR.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class HideInSpr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HideInSpr));
        
        string IMigrationMetadata.Id
        {
            get { return "201609150907049_HideInSpr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
